name: Build Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # نصّب حزم الواجهة وبايثون EXE وباكيج mtkclient من GitHub
        pip install PySimpleGUI pyinstaller git+https://github.com/bkerler/mtkclient.git

    - name: Build EXE
      run: pyinstaller --onefile --windowed flash_tool.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: flash_tool_exe
        path: dist/flash_tool.exe
