name: Build Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install PySimpleGUI
      run: |
        python -m pip install PySimpleGUI

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Install mtkclient
      run: |
        python -m pip install git+https://github.com/bkerler/mtkclient.git

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed Alkhazem_tool.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: alkhazem_tool_exe
        path: dist/Alkhazem_tool.exe
